### ISSUE TITLE
Feature request: filter out gif providers

### ISSUE THREAD

**Issue by ungoldman** [TylerFisher/sill#20]
Hello 👋 

It would be nice to filter out gifs, which look like links to the aggregator but are otherwise contentless -- in particular from media.tenor.com, the service currently used by bsky for attaching gifs. They tend to clutter up the feed.

Example:

![image](https://github.com/user-attachments/assets/3bf43350-35f2-4414-b7af-76f5481ad68e)

Good luck and thanks for the all the work ✌️

**Comment by TylerFisher** [comment]
Fixed!
