### ISSUE TITLE
Bug: Link matching is case-sensitive

### ISSUE THREAD

**Issue by legowerewolf** [TylerFisher/sill#22]
I got two entries for bookshop.org in my feed today. They're the same link, but one of them was `bookshop.org` and one of them was `Bookshop.org`. I think these should be merged.

![image](https://github.com/user-attachments/assets/f2e6584a-9c82-48d6-b6cc-af4202542f34)
![image](https://github.com/user-attachments/assets/660e9c19-c6ed-41f5-aef1-70a40769f8e2)

**Comment by TylerFisher** [comment]
Fixed!
