### ISSUE TITLE
Permalinks for stories / Post & comment from sill?

### ISSUE THREAD

**Issue by ungoldman** [TylerFisher/sill#25]
It would be really cool to be able to click here:

![image](https://github.com/user-attachments/assets/ae862567-8885-4c9d-a76e-58e35d7852b2)

or somewhere in here:

![image](https://github.com/user-attachments/assets/0432b3ad-7017-4820-9fca-f2f3885f1cfb)

and go to a dedicated URL (e.g. https://sill.social/links/0432b3ad, some hash of the URL)

to be able to go to a dedicated page on sill.social showing discussion on this specific story.

It would be _even_ cooler to be able to participate in that discussion _from sill_

**Comment by ungoldman** [comment]
Ah I see some of this is already implemented in https://github.com/TylerFisher/sill/pull/24/commits/5a9cb764eae7c24d2ed531d9789551d13f78c54a#diff-de8b29e9bbb77ba6aeeb1691fa1075ce3ef37b6550fc4e72154a1b0b180762d9R61 👀 

My second suggestion stands though -- would be super cool to be able to post the story or replies to other's posts on the link _from sill_. Maybe that's out of scope for this project 😅

**Comment by TylerFisher** [comment]
Yup, I'll be deploying the permalink route soon!

I've thought about posting back. The multiple-network approach of Sill makes that a little complicated, I'd have to make it clear which account/network you're posting to at any given time.

It feels like a slippery slope, too. Once you're posting from Sill, you probably want full account notifications in Sill. At which point, I've built a full social media client. Maybe that's the direction Sill goes, but that's not where I'm headed at the moment.

**Comment by TylerFisher** [comment]
Released!
