### ISSUE TITLE
Receiving "Application Error" when expanding shared accounts

### ISSUE THREAD

**Issue by steeef** [TylerFisher/sill#29]
I've got both Mastodon and Bluesky connected. When I click on the "Shared by X accounts" button, I see this error:

![Screenshot 2024-12-09 at 08 46 49](https://github.com/user-attachments/assets/b269d405-2153-4c86-b2c3-3793a10801b5)

**Comment by TylerFisher** [comment]
Hey, sorry you're having trouble. This was a bug earlier in the week but as far as I know it's been fixed. Could you try refreshing your cache? If still no luck, could you let me know what browser/OS you're using?

**Comment by steeef** [comment]
Yup, looks fixed. Just had to clear cache first, as you said. Thanks!
