### ISSUE TITLE
"Remember me?" click on `<label>` not functional

### ISSUE THREAD

**Issue by rdmurphy** [TylerFisher/sill#32]
Hello! I just noticed that the "Remember me?" label that's meant to be bound to the checkbox at `/accounts/login` is not actually working.

At first I thought it was just that the checkbox `<input>` does not have `id="remember"` (which I think it should!), but it appears to perhaps be something even more complex because what's visible is not actually a checkbox — it's a styled `<button>`!

I'm not familiar enough with the framework here to follow why that's the case (though I do feel like checkboxes should be actual `<input>` elements to maximize accessibility), but in its current iteration it does appear like the label and the button are not in sync.

**Comment by TylerFisher** [comment]
Oops, I passed the wrong for property to the label, thanks!

RE: it being a button, yikes, I did not realize Radix did that. May need to reassess my checkbox field across the board.

**Comment by TylerFisher** [comment]
Fixed the label in https://github.com/TylerFisher/sill/commit/d20e5e76af7e526641daca1e524070ed9fa29e19, but will open another issue for reassessing <CheckboxField>
